### ISSUE TITLE
회원 마이페이지 만들기

### ISSUE THREAD

**Issue by aqrms** [Kernel360/boot-up1-evereat#27]

**Comment by fepick** [comment]
<img width="692" alt="image" src="https://github.com/Kernel360/boot-up1-evereat/assets/93140874/a80c6f3f-7383-4853-b34e-58ed3c25c805">

- [x] 마이페이지 메인화면 만들기
- [x] 개인 정보 관리 및 수정 - 우무룡
- [x] 주문 내역 - 오동걸
- [x] 현재 진행중인 주문 - 오동걸
- [x] 리뷰 관리 - 우무룡
- [x] 최근에 같이 밥먹은 사람-오동걸
- [x] 밥친구 -오동걸
- [x] 찜한 가게-오동걸

**Comment by fepick** [comment]
내가 작성한 댓글 관리, 장바구니도 마이페이지에 들어갈 수  있을 것 같아요
